import { SidebarItemsType } from "./types";
import { Icons } from "@/components/icons";

export const SIDEBAR_ITEMS: SidebarItemsType[] = [
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: Icons.dashboard,
  },
  {
    title: "Tasks",
    href: "/dashboard/tasks",
    icon: Icons.tasks,
  },
  {
    title: "Views",
    href: "/dashboard/views",
    icon: Icons.calendar,
  },
  {
    title: "Settings",
    href: "/dashboard/settings",
    icon: Icons.settings,
  },
];

export const data = [
  {
    id: "1",
    title: "Design Homepage",
    description: "Create the initial design for the new homepage layout.",
    status: "In Progress",
    priority: "High",
    dueDate: "2024-06-25",
  },
  {
    id: "2",
    title: "Database Backup",
    description: "Perform a full backup of the production database.",
    status: "Pending",
    priority: "Medium",
    dueDate: "2024-06-20",
  },
  {
    id: "3",
    title: "User Feedback Review",
    description: "Review user feedback from the recent product launch.",
    status: "Completed",
    priority: "Low",
    dueDate: "2024-06-18",
  },
  {
    id: "4",
    title: "Marketing Campaign Plan",
    description: "Develop a plan for the upcoming marketing campaign.",
    status: "In Progress",
    priority: "High",
    dueDate: "2024-07-01",
  },
  {
    id: "5",
    title: "Code Refactoring",
    description:
      "Refactor the codebase to improve maintainability and performance.",
    status: "Pending",
    priority: "Medium",
    dueDate: "2024-06-30",
  },
  {
    id: "6",
    title: "Team Meeting",
    description:
      "Schedule and conduct a team meeting to discuss project updates.",
    status: "Scheduled",
    priority: "Low",
    dueDate: "2024-06-22",
  },
  {
    id: "7",
    title: "Customer Support Training",
    description: "Organize training sessions for the customer support team.",
    status: "Pending",
    priority: "High",
    dueDate: "2024-07-10",
  },
  {
    id: "8",
    title: "Bug Fix: Login Issue",
    description: "Fix the login issue reported by multiple users.",
    status: "In Progress",
    priority: "High",
    dueDate: "2024-06-19",
  },
  {
    id: "9",
    title: "SEO Optimization",
    description: "Optimize the website for better search engine ranking.",
    status: "Pending",
    priority: "Medium",
    dueDate: "2024-07-05",
  },
  {
    id: "10",
    title: "Content Strategy",
    description: "Develop a content strategy for the next quarter.",
    status: "Completed",
    priority: "Low",
    dueDate: "2024-06-15",
  },
  {
    id: "11",
    title: "Performance Review",
    description: "Conduct performance reviews for all team members.",
    status: "Scheduled",
    priority: "Medium",
    dueDate: "2024-06-27",
  },
  {
    id: "12",
    title: "Product Launch Preparation",
    description: "Prepare all materials and resources for the product launch.",
    status: "In Progress",
    priority: "High",
    dueDate: "2024-06-29",
  },
  {
    id: "13",
    title: "Security Audit",
    description: "Perform a security audit on the current system.",
    status: "Pending",
    priority: "High",
    dueDate: "2024-07-08",
  },
  {
    id: "14",
    title: "New Hire Onboarding",
    description: "Complete the onboarding process for new hires.",
    status: "Scheduled",
    priority: "Medium",
    dueDate: "2024-06-23",
  },
  {
    id: "15",
    title: "API Documentation",
    description: "Update the API documentation to include recent changes.",
    status: "Pending",
    priority: "Low",
    dueDate: "2024-07-02",
  },
  {
    id: "16",
    title: "Email Campaign",
    description: "Plan and execute an email campaign for existing customers.",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2024-06-28",
  },
  {
    id: "17",
    title: "Server Maintenance",
    description: "Schedule and perform maintenance on the main server.",
    status: "Pending",
    priority: "High",
    dueDate: "2024-06-24",
  },
  {
    id: "18",
    title: "Social Media Posts",
    description:
      "Create and schedule social media posts for the upcoming week.",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2024-06-21",
  },
  {
    id: "19",
    title: "Client Meeting",
    description: "Arrange and attend a meeting with a key client.",
    status: "Scheduled",
    priority: "High",
    dueDate: "2024-06-26",
  },
  {
    id: "20",
    title: "Website Bug Fixes",
    description: "Address and fix reported bugs on the website.",
    status: "In Progress",
    priority: "High",
    dueDate: "2024-06-20",
  },
];
